### ISSUE TITLE
Wait for task to end - not working

### ISSUE THREAD

**Issue by gpogliani** [jlolling/talendcomp_tRunTask#1]
Hi,
i'm using your component but I think there's a couple of issues:
1. line 143 of the Beginjavajet  waitForTaskEnd == true) not false
2. even if I set the waitForTaskEnd still the job waits for the the TAC task to finish

Can you fix it?

Thanks

**Comment by jlolling** [comment]
Hi, thanks for notifying me. I will fix that asap.

**Comment by raosrim** [comment]
Hi,
Is this issue fixed, Looks like similar issues happens to our jobs.

When one tRunTask running it is skipping to next one before finishing the current task.

Error Message:

[ERROR]: de.jlo.talendcomp.tac.TACAction - Request failed: Server error: org.talend.administrator.common.exception.DBException: !!!Cannot retrieve bean: class org.talend.model.tac.conductor.impl.TaskExecutionHistoryImpl!!!","returnCode":1}
java.lang.Exception: Server error: org.talend.administrator.common.exception.DBException: !!!Cannot retrieve bean: class org.talend.model.tac.conductor.impl.TaskExecutionHistoryImpl!!!","returnCode":1}
	at de.jlo.talendcomp.tac.TACAction.executeRequest(TACAction.java:133)
	at de.jlo.talendcomp.tac.RunTask.execute(RunTask.java:56)
...
	at 
[ERROR]: de.jlo.talendcomp.tac.TACAction - Got a still processing error. Stop retrying requests, need a complete status recheck!
java.lang.Exception: Server error: The requested action cannot be carried out because the execution task 
	at de.jlo.talendcomp.tac.TACAction.executeRequest(TACAction.java:133)
	at de.jlo.talendcomp.tac.RunTask.execute(RunTask.java:56)
...
java.lang.Exception: Server error: The requested action cannot be carried out because the execution task 
	at de.jlo.talendcomp.tac.TACAction.executeRequest(TACAction.java:133)
	at de.jlo.talendcomp.tac.RunTask.execute(RunTask.java:56)

**Comment by jlolling** [comment]
Hi,

I kown this bug. It is not the only bug Talend have in it web service interface.
Thats why I have added an option to retry mulitple times the requests.

Another bug is if you run with multiple clients to this web service the service responds “unknown method”.

Thats why I am currently have decided in my project to find another way to start jobs - the TAC is simply not reliable.

Currently we start job every minute and all jobs detect if there is some work to do - or nothing to do.

Anyway, I suggest you open a bug ticket in your Talend support account.

Sometimes it helps to restart the TAC.

Best regards and sorry for having not the best news.
Jan Lolling

**Comment by raosrim** [comment]
Thank you Jan for your quick response.
Please suggest me if my setup is correct.

1. Run task asynchronously (**False**)
2. Wait until the end (**True**)
3. Check time cycle until job is running (Option now showing)
4. Wait until this task and none of the task in the list are running (**False**) should I make this to true?
5. Die on error (**True**)

Currently we have one master job with multiple tRunTask components which run in sequence.

Thank You
Sreenivas

**Comment by raosrim** [comment]
![image](https://user-images.githubusercontent.com/35609371/35176584-e9df9e78-fd2e-11e7-88b3-10a32085624e.png)
